# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Release

on : [push, pull_request]

env:
  ## set env
  git_sha: ${{github.sha}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            src/generated
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - uses: actions/checkout@v4
      - uses: BrycensRanch/read-properties-action@v1
        id: read_properties
        with:
          file: gradle.properties
          all: true
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
      - name: Set version env
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Accept EULA
        run: mkdir -p ./run/testServer && echo "eula=true" > ./run/testServer/eula.txt
      - name: Copy Datapacks
        run: mkdir -p ./run/testServer/world/datapacks && cp ./datapacks/*/*.zip ./run/testServer/world/datapacks/
      - name: Change Minecraft version to maximum bound
        uses: dschanoeh/change-property@v1
        with:
          file: gradle.properties
          property: minecraft_version
          value: ${{steps.read_properties.outputs.upperbound_minecraft_version}}
      - name: Change Fabric API version to maximum bound
        uses: dschanoeh/change-property@v1
        with:
          file: gradle.properties
          property: fabric_version
          value: ${{steps.read_properties.outputs.upperbound_fabric_version}}
      - name: Run Game Test
        timeout-minutes: 5
        run: ./gradlew runTestmodServer
      - name: Change Minecraft version to default
        uses: dschanoeh/change-property@v1
        with:
          file: gradle.properties
          property: minecraft_version
          value: ${{steps.read_properties.outputs.minecraft_version}}
      - name: Change Fabric API version to default
        uses: dschanoeh/change-property@v1
        with:
          file: gradle.properties
          property: fabric_version
          value: ${{steps.read_properties.outputs.fabric_version}}
      - name: Run Game Test
        timeout-minutes: 5
        run: ./gradlew runTestmodServer
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload binaries to release
        uses: actions/upload-artifact@v4
        with:
          name: biome_modifier-${{steps.read_properties.outputs.mod_version}}-${{github.sha}}.jar
          path: build/libs/biome_modifier-${{steps.read_properties.outputs.mod_version}}.jar
          repo-token:  ${{ secrets.ACTION_TOKEN }}
      - name: Upload sources to release
        uses: actions/upload-artifact@v4
        with:
          name: biome_modifier-${{steps.read_properties.outputs.mod_version}}-${{github.sha}}-sources.jar
          path: build/libs/biome_modifier-${{steps.read_properties.outputs.mod_version}}-sources.jar
          repo-token:  ${{ secrets.ACTION_TOKEN }}
